### ISSUE TITLE
Adding music and video sequences on Linux to Dune 2000

### ISSUE THREAD

**Issue by macandchief** [Walkman100/OpenRA-Install-Guide#4]
First of all: I think OpenRA is awesome! Fantastic work, my appreciation to every developer involved in the project.

A simple issue gave me some headaches. I have the original CD but could not install the music and the video sequences (the game showed all the time: Not installed). Maybe two important requirements could/should be pointed out in the description:

- All the filenames for music and video sequences has to be in CAPITAL letters, otherwise Dune 2000 won't recognize them.
- The path on Linux for music and videos are:  ~/.openra/Content/d2k/v2/Music  and  ~/.openra/Content/d2k/v2/Movies   (in the description ~/.openra for Linux is a bit confusing)

I know the path is already in the install file, but someone not familiar with the game (or Linux for that matter) could be lost in the details.

To put it in other words: If you have the .AUD files for Dune 2000 music from the original CD, put them in the Music folder mentioned above (be sure all the filenames are in CAPITAL letters) and do the same - put in the Movies folder in CAPITAL letters - with the video sequences.

I'd like to also mention that the link from the description 81.169.246.181/d2k-music.zip does not seem to work.

Btw thank you for this guide, keep up the great work!

**Comment by Walkman100** [comment]
Wow a month late, sorry I don't check GitHub notifications often.

This guide isn't written with the original discs in mind, but I can see how it would be useful to figure out where everything goes. The information about where files are and how they have to be named to be recognised is supposed to be on the OpenRA wiki, but I can't seem to find it: https://github.com/OpenRA/OpenRA/wiki/Installation - that page was last edited by me so it's quite out of date.

I thought the description in the readme was decently clear, "The folder you will want when installing assets is the `Content` subfolder, this has a folder for each mod (`cnc`, `d2k`, `ra`) with the mod assets contained (`ra` and `d2k` folders additionally have a `v2` folder within)." but I'll write out a tree diagram to make it completely clear.

Regarding the link to the IP address - that was to OpenRA servers, at one point they just removed the ability to download the file automatically but hadn't removed it yet, it seems they removed it eventually.

I'm happy this has helped someone, I try to keep the download instructions & links for all the main mods up to date, but I haven't gotten round to updating my RA2 script yet, I'm hoping they'll fix their build system first (or make it easier to script)

**Comment by Walkman100** [comment]
How's this tree: [README.md#folder-tree](https://github.com/Walkman100/OpenRA-Install-Guide/blob/master/README.md#folder-tree)

**Comment by macandchief** [comment]
Great, thank you for the description and the folder-tree. 

I just thought to mention this issue here because it gave me some struggle (and some hours searching on the web) while I was trying to start the game with music and videos. Just in case someone has the same issue, hopefully it'll be easy to solve thanks to the details here. Cheers.
