### ISSUE TITLE
Downloadlinks broken

### ISSUE THREAD

**Issue by dr-death2** [Walkman100/OpenRA-Install-Guide#5]
Some of the download links used in the scripts are broken 'cause the source changed paths

i.e.:
https://cncnz.com/_files/GDI95.zip and
https://cncnz.com/_files/NOD95.zip

are now to be found at
https://files.cncnz.com/cc1_tiberian_dawn/full_game/GDI95.zip and
https://files.cncnz.com/cc1_tiberian_dawn/full_game/NOD95.zip

and others fail too.

**Comment by Walkman100** [comment]
Merged, thanks
