### ISSUE TITLE
Destination directories changed in recent linux distributions

### ISSUE THREAD

**Issue by dr-death2** [Walkman100/OpenRA-Install-Guide#6]
The scripts install the files to `~/.openra/*`. In newer distributions such as Debian or Linux Mint (and probably also Ubuntu) the files are not found by the game because it expects them at `~/.config/openra/*`.

So the scripts must be either changed to generally use the new location or to figure out which of the two options to use in a certain case.

**Comment by Walkman100** [comment]
Yeah, they changed on Windows too

**Comment by Walkman100** [comment]
Ok, updated Windows & Linux directories, but I'm still not 100% sure how to handle the `$XDG_CONFIG_HOME` stuff.

**Comment by dr-death2** [comment]
@Walkman100: merging the three commits from PR #7 and your commit a32a2baf632a53955887e4c6dcd72410ed9bbcce resolves these issues on Linux and Windows
